baseURL = 'https://www.louisestrawbridge.com/'
languageCode = 'en-us'
title = 'Louise Strawbridge Artist Portfolio'
theme = ['PaperMod']
[Params]
#  label.icon = '/images/louisestrawbridge.png'
  label.text = 'Louise Strawbridge'
  # disableThemeToggle = true
  defaultTheme = 'light'
#   comingSoon = true
  # profileMode = true
  mainSections = ['gallery']

[menu]
[[menu.main]]
    name = 'Work'
    url = '/gallery/'
    weight = 20
[[menu.main]]
    name = 'Resume'
    url = '/resume/'
    weight = 30
[[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 40
[[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 50