baseURL = 'https://www.louisestrawbridge.com/'
title = 'Louise Strawbridge Artist Portfolio'
theme = ['gallery']
timeout = "120000"
languageCode = "en-us"
copyright = "© Louise Strawbridge"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "America/New_York"

[params]
  title = "Louise Strawbridge Artist Portfolio"
  description = "The work of Louise Strawbridge"
#   defaultTheme = "dark"

[author]
  name = "Louise Strawbridge"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
[[menu.footer]]
    name = 'Resume'
    url = '/resume/'
    weight = 30
[[menu.footer]]
    name = 'About'
    url = '/about/'
    weight = 20
[[menu.footer]]
    name = 'Contact'
    url = '/contact/'
    weight = 50

[[menu.collage]]
    name = 'Expanding My Horizons'
    url = '/collage/expanding_my_horizons/'
    weight = 30
[[menu.collage]]
    name = 'Old Book Covers'
    url = '/collage/old_book_covers/'
    weight = 30
[[menu.collage]]
    name = 'Red Brings Good Fortune'
    url = '/collage/red_brings_good_fortune/'
    weight = 30
[[menu.collage]]
    name = 'Seeing in the Dark'
    url = '/collage/seeing_in_the_dark/'
    weight = 30
[[menu.collage]]
    name = 'Stuck'
    url = '/collage/stuck/'
    weight = 20
[[menu.collage]]
    name = 'Transparent'
    url = '/collage/transparent/'
    weight = 10

[[menu.sculpture]]
    name = 'Boxes'
    url = '/sculpture/boxes/'
    weight = 30
[[menu.sculpture]]
    name = 'Hands'
    url = '/sculpture/hands/'
    weight = 20
[[menu.sculpture]]
    name = 'Poetry People'
    url = '/sculpture/poetry_people/'
    weight = 10
[[menu.sculpture]]
    name = 'Stele'
    url = '/sculpture/stele/'
    weight = 50
[[menu.sculpture]]
    name = 'Vessels'
    url = '/sculpture/vessels/'
    weight = 30