baseURL = 'https://www.louisestrawbridge.com/'
languageCode = 'en-us'
title = 'Louise Strawbridge Artist Portfolio - Dev'
theme = ['PaperMod']
[Params]
#  label.icon = '/images/louisestrawbridge.png'
  label.text = 'Louise Strawbridge'
  # disableThemeToggle = true
  defaultTheme = 'light'
#   comingSoon = true
  # profileMode = true
  mainSections = ['gallery']

[menu]
[[menu.main]]
    identifier = "work"
    name = 'Work'
    url = '/gallery/'
    weight = 20
  
[[menu.main]]
    identifier = 'assemblage'
    name = 'Assemblage'
    url = '/gallery/assemblage/'
    parent = 'work'
    weight = 21
[[menu.main]]
    identifier = 'artistsbooks'
    name = "Artist's Books"
    url = '/gallery/artistsbooks/'
    parent = 'work'
    weight = 22
[[menu.main]]
    identifier = 'collage'
    name = 'Collage'
    url = '/gallery/collage/'
    parent = 'work'
    weight = 23

[[menu.main]]
    name = 'Resume'
    url = '/resume/'
    weight = 30
[[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 40
[[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 50