title = 'Louise Strawbridge Artist Portfolio'

[params]
  env = "production"
  plausible_domain = "louisestrawbridge.com"
  plausible_advanced = true

# [services]
  # [services.googleAnalytics]
    # ID = 'G-JMTEM65W38'