# This is a basic workflow to help you get started with Actions

name: Create gallery template

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      galleryName:
        description: 'Gallery Name, with parent gallery preceding if desired, ie: `collage/new-gallery`'     
        required: true
        # default: 'warning'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"

      - name: Create New Gallery directory
        run: hugo new content ${{ github.event.inputs.galleryName }}/index.md
      
      - name: Add, commit, and push
        uses: actions4git/add-commit-push@v1.0.0
        with:
          commit-message: "Automated Changes occured. Added new content ${{ github.event.inputs.logLevel }}/index.md" # optional, default is Automated changes
    
