name: Create gallery template

on:
  workflow_dispatch:
    inputs:
      galleryName:
        description: 'Gallery Name, with parent gallery preceding if desired, ie: `collage/new-gallery`'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          ref: 'main' # Updated to use 'main' branch

      # Setup Hugo
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"

      # Create New Gallery directory
      - name: Create New Gallery directory
        run: hugo new content/${{ github.event.inputs.galleryName }}/index.md

      # Commit and push changes to main
      - name: Add, commit, and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated Changes: Added new content at ${{ github.event.inputs.galleryName }}/index.md"
          branch: main  # Updated to push to 'main' branch
